apiVersion: run.tanzu.vmware.com/v1alpha1
kind: TanzuKubernetesCluster                   
metadata:
  # Name of cluster example tkg-cluster-01
  name: clustername
  # vSphere Workload Management Nameapace to deploy cluster to
  namespace: vspherenamespace
settings:
  defaultClass: vsphere-with-kubernetes                         
spec:
  distribution:
    version: clusterversion                             
  topology:
    controlPlane:
      # Number of Nodes in Controlplane
      count: 3                                 
      class: best-effort-tsmfe  
      #vSphere storage class to use get this from vsphere admin  
      storageClass: vsphere-with-kubernetes 
    workers:
      #
      count: 1                
      class: best-effort-tsmfe
      #vSphere storage class to use get this from vsphere admin
      storageClass: vsphere-with-kubernetes 
  settings:
    storage:
    #  classes: ["vsphere-with-kubernetes"]      #Named PVC storage classes
      defaultClass: vsphere-with-kubernetes     #Default PVC storage class